spring:
  datasource:
    url: jdbc:mysql://localhost:3306/secondhand_house?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: qiQi1314**00
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    baseline-on-migrate: true
    default-schema: secondhand_house
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  jackson:
    default-property-inclusion: non_null
server:
  port: 8080
