spring:
  datasource:
    url: jdbc:mysql://localhost:3306/h01?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: qiQi1314**00
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    baseline-on-migrate: true
    default-schema: h01
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  jackson:
    default-property-inclusion: non_null
server:
  port: 8080
assistant:
  ai:
    base-url: "https://api.moonshot.cn/v1"
    api-key: sk-i38TXYv1Zv6Qnd3jE3Zq3X6mr6gu7YE4nmerjKJtgIESekZn
    model: "kimi-k2-turbo-preview"
